### ISSUE TITLE
Enquiry about one-step forecasting

### ISSUE THREAD

**Issue by appreciator** [Helloworld2345567/Google_TiDE_implementation#1]
Hi! Your code for the pytorch implementation of TiDE is very awesome. Thanks for sharing your code! I believe that it will help a lot of people.

I am a beginner of the time-series prediction using machine learning. Would you mind kindly telling me that whether your code support one-step forecasting?  Or it only supports multi-step forecasting?

I am looking forward to your reply. I would sincerely appreciate your help.

**Comment by Helloworld2345567** [comment]
Thank you for your kind words regarding my code, I'm delighted to hear that it has been helpful to you.

Regarding your question, I wanted to let you know that TiDE fully supports one-step forecasting. To achieve this, you simply need to set the Lookback parameter to one. I should note that I haven't extensively tested TiDE for one-step forecasting, it's mainly designed for longer time series prediction problems where one-step forecasting isn't typically required.

Finally, I would also like to mention that while my implementation of TiDE may not be perfect, especially when it comes to incorporating static covariates or Attributes, you can certainly modify the model based on the official code to make it work for your specific use case.

**Comment by appreciator** [comment]
Thank you so much for your quick reply and detailed explanation. It's so kind of you.
